### ISSUE TITLE
Fix E501 line too long errors

### ISSUE THREAD

**Issue by bremme** [alliander-opensource/openstf#5]
At present we ignore the maximum line length while running the linting step of our CI/CD. There are about 110 violations at present. Fix the long lines and remove the E501 ignore code from our `setup.cfg`

**Comment by FrankKr** [comment]
is this now fixed with the auto-black-er?

**Comment by bremme** [comment]
Not completely I think. It seems that `black` is not able to fix this in every? case. Even after running `black` there are still 121 violation (they have increases I guess). The problem seems to be docstrings. Black does not format docstrings properly. Perhaps we should use another tool for this. Or let the Linting step fail if these lines are too long?

**Comment by FrankKr** [comment]
I'm closing this issue. If syntax formatting conforms to Black, it's fine.
Don't think we should be adding additional requirements. If Black's OK, we should be OK.
