### ISSUE TITLE
[Feature] Implement Logger in new pipeline

### ISSUE THREAD

**Issue by JanMaartenvanDoorn** [alliander-opensource/openstf#72]
**WHAT:** 
In the new pipeline we use print statements for logging. Implement a nice structlog logger. This functionality should be part of openstf instead of ktpbase.
An example is available in ktpbase.log -> logging

**HOW:**
- Look at old pipeline on how to import the structlog-based logger
- Replace print statements with proper logging calls (logging.info, logging.debug, logging.warning, …)
- Use warnings, errors etc. when appropriate
- In the pipeline call the structlog.get_logger() method to get a logger instead of calling ktpbase.
- If making changes to the pipeline is not a lot of work, replace the ktpbase calls in other parts of the code with structlog calls.

**TEST:**
-	All logging in the new pipeline is carried out by the logging-object, no prints are used
-	Logging is not dependent on ktpbase

**Comment by FrankKr** [comment]
I believe this issue to be obsolete
