### ISSUE TITLE
[Feature] Hyperparameter optimization pipeline compatible with new sklearn models

### ISSUE THREAD

**Issue by JanMaartenvanDoorn** [alliander-opensource/openstf#83]
WHAT: With the new pipeline based on sklearn model updating the hyperparameter optimization pipeline is necessary. Here we implement a new pipeline that works with the new sklearn models.

HOW:
- have a look at the examples here: https://scikit-learn.org/stable/modules/grid_search.html 
-  Focus here on the parameter tuning and try to keep the pipeline lean
-  Direct DB calls from the pipeline are undesired, training data should be an input argument
- Also have a look at the method we used with the old pipeline: https://github.com/alliander-opensource/short-term-forecasting/blob/develop/openstf/pipeline/optimize_hyperparameters.py
- Make a plan how to implement the new pipeline
- Featureset optimization is a nice to too have but not strictly necessary, make a new story if you skip this.
- Implement it

TEST:
- hyperparameters of the sklearn models can be tuned automatically with a specialized pipeline

**Comment by FrankKr** [comment]
added link to old pipeline: https://github.com/alliander-opensource/short-term-forecasting/blob/develop/openstf/pipeline/optimize_hyperparameters.py
