### ISSUE TITLE
[Feature] Make tracy compatible with new pipeline

### ISSUE THREAD

**Issue by JanMaartenvanDoorn** [alliander-opensource/openstf#90]
WHAT: To manually train a model or optimize hyper parameters we have tracy. Tracy still calls the old pipelines. Change this to the new pipelines.

HOW:
- have a look at the tracy code (task: run_tracy)
- change the "train_model_for_specific_pid" and the "optimize_hyper_parameters_for_specifc_pid" function such that they use the new pipeline
- Check if the "allowed functions" in tracy are still up to date

TEST:
- tracy retrains models with new pipeline
- tracy optimizes hyper parameters with new pipeline

**Comment by FrankKr** [comment]
I think Bram started working on this
https://github.com/alliander-opensource/short-term-forecasting/tree/feature-KTPS-1428-make-tracy-compatible-with-sklearn-pipelines

**Comment by FrankKr** [comment]
fixed by #106
